import { useState } from "react";
import Head from "next/head";
import { BsFillMoonStarsFill, BsFillSunFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillInstagram, AiOutlineMail } from "react-icons/ai";
import Image from "next/image";
import myphoto from "../public/myphoto.png";
import iris from "../public/web/iris.png";
import dapoint from "../public/web/dapoint.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Musyaffa's Web Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white dark:bg-gray-900 px-10 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-white">musyaffa's web profile</h1>
            <ul className="flex items-center">
              <li className="cursor-pointer text-2xl">
                {!darkMode ? (
                  <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} />
                ) : (
                  <BsFillSunFill
                    className="text-white"
                    onClick={() => setDarkMode(!darkMode)}
                  />
                )}
              </li>
              <li>
                <a
                  className="select-none bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 ml-8 rounded-md"
                  href="//cv.aksel.co.id/r/i5y468"
                  target={"_blank"}
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 dark:text-teal-400 font-medium md:text-6xl">
              Musyaffa Choirun Man
            </h2>
            <h3 className="text-2xl dark:text-white py-2 md:text-3xl">
              Front End Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Code Enthusiast who loves on front - end developing using React JS,
              Vue JS, and Flutter. But i also have back - end skills to creating
              aplication using Laravel. Contact me down below and let's get
              cracking!
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <a href="//linkedin.com/in/musyaffa/">
              <AiFillLinkedin />
            </a>
            <a href="mailto:musyaffa@student.uns.ac.id">
              <AiOutlineMail />
            </a>
            <a href="//www.instagram.com/musyaffa44/">
              <AiFillInstagram />
            </a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={myphoto} className="w-80 md:w-96" />
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <a href="//m3119063.mhs.d3tiuns.com/">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  src={iris}
                />
              </a>
              <a href="//m3119063.mhs.d3tiuns.com/">
                <p className="text-md dark:text-white mt-3 py-1 md:text-xl">IRIS</p>
              </a>
              <p className="text-sm py-1 mt-2 leading-6 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-md text-justify">
                A web-based system that is used to provide online
                and integrated services to research lecturers or service
                lecturers in terms of proposals to research and community
                service information at the university
              </p>
              <p className="text-sm py-1 leading-6 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-md text-justify">Created using : Laravel, Bootstrap, and PHP Language</p>
            </div>
            <div className="basis-1/3 flex-1">
              <a href="//dapoint.netlify.app/">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  src={dapoint}
                />
              </a>
              <p className="text-md dark:text-white mt-3 py-1 md:text-xl">Dapoint</p>
              <p className="text-sm py-1 mt-2 leading-6 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-md text-justify">
              Applications for stores provide gifts to their customers in the form of vouchers that are easily accessible and easy to reedem. Aims to increase customer loyalty to related stores
              </p>
              <p className="text-sm py-1 leading-6 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-md text-justify">Created using : Vue JS, Vuetify, Vuex and Javascript Language</p>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
